services:
  - type: web
    name: quiz-generator
    env: node
    buildCommand: npm run build
    startCommand: npm run start:render
    envVars:
      - key: NODE_ENV
        value: production
    healthCheckPath: /health
